name: Docker Image CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: [published]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Determine Docker Tag
        id: tag
        run: |
          if [[ $GITHUB_EVENT_NAME = 'release' ]]; then
            echo "::set-output name=DOCKER_TAG::${{ github.event.release.tag_name }}"
          else
            echo "::set-output name=DOCKER_TAG::pr-${{ github.event.pull_request.number }}"
          fi

      - name: Quay login
        run: |
          echo "${{ secrets.QUAY_TOKEN_GHA }}" | docker login --username "${{ secrets.QUAY_USERNAME_GHA }}"  --password-stdin quay.io

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 743287612805.dkr.ecr.us-west-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=raw,value={{sha}}
            type=raw,value=${{ steps.tag.outputs.DOCKER_TAG }}
          images: |
            quay.io/soxhub/edgurgle-poxa
            743287612805.dkr.ecr.us-west-2.amazonaws.com/edgurgle-poxa

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Prisma Cloud Scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.4.0
        continue-on-error: true
        with:
          pcc_console_url: ${{ secrets.PRISMA_CONSOLE_URL }}
          pcc_user: ${{ secrets.PRISMA_ACCESS_KEY }}
          pcc_pass: ${{ secrets.PRISMA_SECRET_KEY }}
          image_name: quay.io/soxhub/edgurgle-poxa:${{ steps.tag.outputs.DOCKER_TAG }}